# Generated by Django 5.2.9 on 2025-12-18 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя читателя')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя автора')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='Страна')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'country'], name='books_autho_name_cf8bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Название')),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ISBN')),
                ('publication_year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2100)], verbose_name='Год издания')),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество страниц')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('non_fiction', 'Научная литература'), ('fantasy', 'Фэнтези'), ('sci_fi', 'Научная фантастика'), ('mystery', 'Детектив'), ('romance', 'Роман'), ('thriller', 'Триллер'), ('biography', 'Биография'), ('history', 'История'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Жанр')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-publication_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата выдачи')),
                ('planned_return_date', models.DateField(db_index=True, verbose_name='Планируемая дата возврата')),
                ('actual_return_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Фактическая дата возврата')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookloan', to='books.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Выдача книги',
                'verbose_name_plural': 'Выдачи книг',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year', 'pages'], name='books_book_publica_e5a085_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'genre'], name='books_book_author__2ed2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='bookloan',
            index=models.Index(fields=['book', 'actual_return_date'], name='books_bookl_book_id_db8b58_idx'),
        ),
        migrations.AddIndex(
            model_name='bookloan',
            index=models.Index(fields=['reader', 'actual_return_date'], name='books_bookl_reader__6dc491_idx'),
        ),
        migrations.AddIndex(
            model_name='bookloan',
            index=models.Index(fields=['planned_return_date', 'actual_return_date'], name='books_bookl_planned_d6fc0e_idx'),
        ),
    ]
